- name: signature mediawiki 01.01.00
  file:
    path: /etc/conf_centos/md4_mediawiki.01.01.00_centos_7
    state: touch

- name: signature php7.4
  file:
    path: /etc/conf_centos/md4_php7.4_centos_7
    state: touch
  notify: restart httpd
